# @package _global_
defaults:
  - override /hydra/launcher: submitit_slurm

hydra:
  launcher:
    partition: gpu
    gres: "gpu:a100:2"
    cpus_per_task: 8
    mem_gb: 32
    timeout_min: 10080
    setup:
      - ml lang
      - ml Miniforge3
      - conda activate pisotorch
      - export FLUIDGYM_LOCAL_DATA_PATH=/scratch/hpc-prf-reinfphys/reinfph2/git_projects/rl-fluid-bench/local_data